# Generated by Django 5.1.4 on 2026-05-26 15:46

import django.db.models.deletion
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pin', models.BooleanField(default=False)),
                ('cover', models.CharField(blank=True, default='linear-gradient(135deg,#d957a6,#6e1d1d)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pin', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, default='', max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('Synthwave', 'Synthwave'), ('Ambient', 'Ambient'), ('Lo-fi', 'Lo-fi'), ('Drone', 'Drone'), ('Folk-tronic', 'Folk-tronic'), ('Post', 'Post'), ('Spoken', 'Spoken'), ('Rock', 'Rock'), ('Pop', 'Pop'), ('Electronic', 'Electronic'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Other', 'Other')], default='Other', max_length=40)),
                ('duration', models.PositiveIntegerField(default=0, help_text='seconds')),
                ('file', models.FileField(upload_to=music.models.track_file_path)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=music.models.cover_file_path)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='#6e1d1d', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistTrack', to='music.track'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('user', 'file_sha256'), name='uniq_user_file_sha256'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='uniq_playlist_track'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='uniq_user_track_favorite'),
        ),
    ]
