# Generated by Django 5.1.4 on 2026-05-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]


